[audio]
enable_overdrive = true

[bar]
order = [ "top" ]

    [bar.top]
    background_opacity = 1
    capsule = true
    capsule_border = "outline"
    capsule_opacity = 0.64999998547136784
    capsule_padding = 8.0
    capsule_thickness = 0.64999998919665813
    center = [ "group:g2" ]
    end = [ "group:g3", "group:g5", "battery", "group:g4" ]
    layer = "top"
    margin_ends = 150
    padding = 8
    radius_top_left = 80
    radius_top_right = 80
    scale = 0.90000000596046448
    start = [ "brightness", "workspaces", "group:g1" ]
    thickness = 32

        [[bar.top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "outline"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "media", "audio_visualizer" ]
        opacity = 0.64999997615814209
        padding = 8.0

        [[bar.top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "outline"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "control-center", "clock", "theme_mode" ]
        opacity = 0.64999997615814209
        padding = 8.0
        radius = 6.0
        widget_spacing = 12

        [[bar.top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "outline"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "network", "bluetooth" ]
        opacity = 0.64999997615814209
        padding = 8.0

        [[bar.top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "outline"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "notifications", "tray" ]
        opacity = 0.64999997615814209
        padding = 8.0

        [[bar.top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "outline"
        enabled = true
        fill = "surface_variant"
        id = "g5"
        members = [ "widget", "input_volume" ]
        opacity = 0.64999997615814209
        padding = 8.0

[brightness]
enable_ddcutil = true
sync_all_monitors = true

[calendar]
enabled = true
event_date_format = "%Y.%m.%d"
refresh_minutes = 5

    [calendar.account.avvale]
    color = "#3B8B05"
    name = "avvale"
    server_url = "https://outlook.office365.com/owa/calendar/b277bcbb7aa344bdbad82bf1d115dad9@avvale.com/f7a112a8498f40d4a4ee0676951b58922345964236348460692/calendar.ics"
    type = "ics"

    [calendar.account.feraxhp]
    color = "#FB2626"
    name = "[radicale] feraxhp"
    provider = "custom"
    server_url = "https://cal.feraxhp.com/feraxhp/12fe3e5c-33a3-271f-3e97-3ab74dac2ac5/"
    type = "caldav"
    username = "feraxhp"

[config]

[control_center]
hidden_tabs = [ "audio" ]

    [control_center.calendar]
    show_week_numbers = true

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "yocraft/custom-shortcut:shortcut"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[hooks]
theme_mode_changed = "~/.config/niri/themes/toggle.sh"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[location]
address = "Mosquera"
custom_schedule = true
sunrise = "08:30"
sunset = "17:00"

[lockscreen]
wallpaper = "/home/feraxhp/images/walls/cloud-coffee.jpg"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-3", "lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-3"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 764.0
    cy = 836.0
    output = "eDP-1"
    placement_height = 1018.0
    placement_width = 1527.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 794.0
    cy = 1415.0
    output = "winit"
    placement_height = 1597.0
    placement_width = 1587.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.88999998010694981
max_visible = 2
scale = 0.85000000521540642

[plugin_settings."yocraft/custom-shortcut"]
icon = "network"
label = "Hopp"
onclick_cmd = "pkill hopp || ~/apps/hopp.agent"

[plugins]
enabled = [ "cleboost/zed-provider", "blackbartblues/audio-switcher" ]

[shell]
app_icon_color = "primary"
app_icon_colorize = true
avatar_path = "/home/feraxhp/.config/noctalia/images/face.png"
corner_radius_scale = 2.0
font_family = "JetBrains Mono"
niri_overview_type_to_launch_enabled = true
screen_time_enabled = true

    [shell.panel]
    open_near_click_launcher = true

[templates]

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Peach"
mode = "auto"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty", "gtk3", "gtk4", "qt" ]
    community_ids = [ "gimp" ]

[wallpaper]
directory = "/home/feraxhp/images/walls"

    [wallpaper.default]
    path = "/home/feraxhp/images/walls/cloud-coffee.jpg"

    [wallpaper.last]
    path = "/home/feraxhp/images/walls/cloud-coffee.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/feraxhp/images/walls/cloud-coffee.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/feraxhp/images/walls/cloud-coffee.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/feraxhp/images/walls/catppuccin_mocha_a_drawing_of_a_wolf_and_a_lion.png.png"

[widget.audio_visualizer]
show_when_idle = true

    [widget.audio_visualizer.actions]
    left = "panel-toggle control-center media"
    right = "media toggle"

[widget.clock]
format = "• %H:%M:%S • %d %b, %a •"

[widget.control-center]
custom_image = "/home/feraxhp/.config/noctalia/images/face.png"
icon_color = "primary"

[widget.media]
album_art_only = true

[widget.network]
icon_color = "tertiary"
show_label = false
vpn_status = "both"

[widget.notifications]
hide_when_no_unread = true

[widget.theme_mode]
font_family = "JetBrains Mono Medium"
icon_color = "primary"

    [widget.theme_mode.actions]
    back = "exec noctalia msg theme-mode-set auto"
    left = "panel-toggle control-center system"
    right = "theme-mode-toggle"

[widget.widget]
type = "blackbartblues/audio-switcher:widget"

[widget.workspaces]
label_source = "name"
max_label_chars = 4
